# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.log_p_r <- function(beta_r, A_r, C_r, L) {
    .Call(`_pnnclass_log_p_r`, beta_r, A_r, C_r, L)
}

.data_topology <- function(X_trn, y_trn, distance) {
    .Call(`_pnnclass_data_topology`, X_trn, y_trn, distance)
}

.loocv <- function(dt, beta_hat) {
    .Call(`_pnnclass_loocv`, dt, beta_hat)
}

.predict_test <- function(model, X_tst) {
    .Call(`_pnnclass_predict_test`, model, X_tst)
}

